package com.varel.gereon.components.IMU.Constants;

public enum LSM9DS1_Magnetometer_Gain {
    LSM9DS1_MAGNETOMETER_4GAUSS,
    LSM9DS1_MAGNETOMETER_8GAUSS,
    LSM9DS1_MAGNETOMETER_12GAUSS,
    LSM9DS1_MAGNETOMETER_16GAUSS
}
